version: 2.1


orbs:

  aws-cli: circleci/aws-cli@2.0.3


commands:

  destroy_environment:
    parameters:
      ID:
        type: string
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
          # ${CIRCLE_WORKFLOW_ID:0:7} takes the first 7 chars of the variable CIRCLE_CI_WORKFLOW_ID 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-<< parameters.ID >>

jobs:
  print_greetings:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Hello World"

  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
              --region us-east-1
      - destroy_environment
          
     
     


  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["4b:db:62:12:c6:1f:60:67:6d:6a:89:3a:14:44:52:14"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory playbook.yml

  # Exercise: Smoke Testing
  smoke_test:
    docker: 
      - image: amazon/aws-cli
    steps:
      - run: apk add --update curl
     
      - run: 
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # I am testing if the website below exists
            if curl -s --head ${URL}
            then
              return 1
            else
              return 1
            fi 
      - destroy_environment:
          ID: ${CIRCLE_WORKFLOW_ID:0:7}
        


      
workflows:
  my_workflow:
    jobs:
      - print_greetings
      - create_infrastructure
      - smoke_test